// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sigylynftjsczhuzvbax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpZ3lseW5mdGpzY3podXp2YmF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2MjE5NjEsImV4cCI6MjA3NjE5Nzk2MX0.SPh7VDlubphDOk0gV3jiIUCiSAoe1jAW5KEC_TJWiWs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});